"""rating table

Revision ID: 37fbe8e2b776
Revises: 8979392e2b8c
Create Date: 2026-07-27 15:37:49.070580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fbe8e2b776'
down_revision: Union[str, Sequence[str], None] = '8979392e2b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flag',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('flag_category', sa.Enum('NEEDS_CHANGES', 'INAPPROPRIATE', 'STUDY_ME', name='flag_category', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_index('ix_flag_user_category', 'flag', ['user_id', 'flag_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flag_user_category', table_name='flag')
    op.drop_table('flag')
    # ### end Alembic commands ###
