"""add_user_ai_providers_and_integrations

Revision ID: 8979392e2b8c
Revises: d8fff3c30738
Create Date: 2026-06-20 17:29:21.405298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import repz


# revision identifiers, used by Alembic.
revision: str = '8979392e2b8c'
down_revision: Union[str, Sequence[str], None] = 'd8fff3c30738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ai_providers',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('api_key', repz.ai.crypto.EncryptedString(length=500), nullable=True),
    sa.Column('api_base', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ai_integrations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['user_ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ai_integrations')
    op.drop_table('user_ai_providers')
    # ### end Alembic commands ###
