"""add category_lists

Revision ID: d8fff3c30738
Revises: 6cc27a5a6ca8
Create Date: 2026-05-23 18:18:51.099392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fff3c30738'
down_revision: Union[str, Sequence[str], None] = '6cc27a5a6ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_lists',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_list_name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_list_association',
    sa.Column('category_list_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.category_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_list_id'], ['category_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_list_id', 'category')
    )
    op.create_unique_constraint(None, 'languages', ['language'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'languages', type_='unique')
    op.drop_table('category_list_association')
    op.drop_table('category_lists')
    # ### end Alembic commands ###
