"""update schema and seed languages

Revision ID: de1c891cb8ed
Revises: b5c51318dc36
Create Date: 2026-05-19 16:03:16.171266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1c891cb8ed'
down_revision: Union[str, Sequence[str], None] = 'b5c51318dc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('language', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('language'),
    sa.UniqueConstraint('language')
    )
    op.create_table('user_languages_association',
    sa.Column('language', sa.String(length=35), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language'], ['languages.language'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('language', 'user_id')
    )
    op.create_table('audio',
    sa.Column('audio_id', sa.Integer(), sa.Identity(always=False), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=40), nullable=False),
    sa.Column('audio_text', sa.Text(), nullable=True),
    sa.Column('object_key', sa.String(length=1000), nullable=False),
    sa.Column('public_url', sa.String(length=1500), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tts_engine', sa.String(length=80), nullable=True),
    sa.Column('tts_voice', sa.String(length=160), nullable=True),
    sa.Column('language', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['language'], ['languages.language'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audio_id'),
    sa.UniqueConstraint('object_key', name='uq_audio_object_key')
    )
    op.create_index('ix_audio_lookup', 'audio', ['question_id', 'part', 'language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audio_lookup', table_name='audio')
    op.drop_table('audio')
    op.drop_table('user_languages_association')
    op.drop_table('languages')
    # ### end Alembic commands ###
