version: '3.8'
services:
  reps:
    restart: on-failure:5
    depends_on:
      - postgres
    build:
      context: /home/z/projects/reps-project
      dockerfile: /home/z/projects/reps-project/Dockerfile
    networks:
      proxy-network:  
        ipv4_address: 10.5.0.4
      rep-network:
        ipv4_address: 10.10.0.4
    ports:
      - '5000:5000'
      - '6001:6001'
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi.py
    volumes:
      - ./doSomeReps:/app
    command: flask run --host=0.0.0.0 --port=5000
 
  reps_dev:
    build:
      context: /home/z/projects/reps-project
      dockerfile: /home/z/projects/reps-project/Dockerfile
      args:
       - NODE_ENV=development
    networks:
      proxy-network:
        ipv4_address: 10.5.0.5
      rep-network:
        ipv4_address: 10.10.0.5     
    ports:
      - '5001:5001'
      - '5678:5678'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - NODE_ENV=development
    volumes:
      - ./doSomeReps:/app
    command: python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --host=0.0.0.0 #--debugger

  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     SA_PASSWORD: ${SQL_SERVER_SA_PASSWORD}
  #     ACCEPT_EULA: "Y"
  #   networks:
  #     rep-network:
  #       ipv4_address: 10.5.0.16
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - mssql_data:/var/opt/mssql

  postgres:
    image: postgres:latest
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      rep-network:
        ipv4_address: 10.10.0.2
    ports:
      - "5432:5432"
    volumes:
      - rep_pg_data:/var/lib/postgresql/data


volumes:
  mssql_data:
    name: "reps-db"
  rep_pg_data:
    name: "rep"

networks:
  rep-network:
    driver: bridge
    name: rep-network
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
  proxy-network:
    external: true
