apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-jackie-pvc
  namespace: reps-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 5Gi