apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-hatchet-pvc
  namespace: hatchet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain-hatchet
  resources:
    requests:
      storage: 5Gi
