apiVersion: v1
kind: Service
metadata:
  name: hatchet-postgres
  namespace: hatchet
spec:
  selector:
    app: hatchet-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  type: ClusterIP
