apiVersion: apps/v1
kind: Deployment
metadata:
  name: reps-dev
  namespace: reps-dev
  labels:
    app: reps-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reps-dev
  template:
    metadata:
      labels:
        app: reps-dev
    spec:
      imagePullSecrets:
        - name: regcred

      containers:
        - name: reps
        #  NEED TO UPDATE TO USE TAGS so you dont pull each time!
          image: docker.io/oktobrfest/reps:latest
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent

# HANDLED IN DOCKER IMAGE NOW:
          # Your compose used "command: sh entrypoint.sh"
          # Use the full path that exists in your image:
          # command: ["/bin/sh","/app/entrypoint.sh"]

# UNTESTED:
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   runAsNonRoot: true
          #   runAsUser: 10001
          #   runAsGroup: 10001
          #   readOnlyRootFilesystem: true

          env:
            - name: APP_PORT
              value: "5559"
            - name: FLASK_ENV
              value: "dev"
            - name: FLASK_DEBUG
              value: "1"
            - name: FLASK_APP
              value: "wsgi.py"
            - name: NODE_ENV
              value: "dev"
            - name: IDE
              value: "vscode"
          
          envFrom:
            - secretRef:
                name: reps-dev-secrets
            - configMapRef:
                name: reps-dev-config

          ports:
            - containerPort: 5554
              name: http

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
