apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: reps-prod
spec:
  selector:
    app: postgresql
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  type: ClusterIP