# /home/x/repos/doSomeReps/k3/prod/db/rep-db-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: reps-prod
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
        fsGroupChangePolicy: "OnRootMismatch"

      initContainers:
        - name: fix-log-perms
          image: alpine:3.20
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -lc
            - >
              mkdir -p /var/lib/postgresql/logs &&
              chown -R 70:70 /var/lib/postgresql/logs &&
              chmod -R 0775 /var/lib/postgresql/logs
          volumeMounts:
            - name: pg-logs
              mountPath: /var/lib/postgresql/logs

      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          args: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
          env:
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: postgres-auth, key: POSTGRES_DB } }
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: postgres-auth, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: postgres-auth, key: POSTGRES_PASSWORD } }
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: pg
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
              readOnly: true
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: pg-logs
              mountPath: /var/lib/postgresql/logs

          readinessProbe:
            exec:
              command: ["sh","-lc","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h 127.0.0.1 -p 5432"]
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits: { cpu: "500m", memory: "1Gi" }

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-config
          configMap:
            name: postgres-config
            items:
              - key: postgresql.conf
                path: postgresql.conf
        - name: postgres-init
          configMap:
            name: postgres-config
            items:
              - key: 00-init-extensions.sql
                path: 00-init-extensions.sql
        - name: pg-logs
          persistentVolumeClaim:
            claimName: postgres-logs-pvc
