apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: reps-prod
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"  # 10% of a CPU core
          limits:
            memory: "256Mi"
            cpu: "500m"  # 50% of a CPU core

        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 10
        
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 20

        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc