apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: reps-prod
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:      
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - jackie

      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"  
          limits:
            memory: "1Gi"
            cpu: "1"  

        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 10
        
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 20

# UNNECESSARY!:
      #   volumeMounts:
      #   - name: redis-data
      #     mountPath: /data
      # volumes:
      # - name: redis-data
      #   persistentVolumeClaim:
      #     claimName: redis-pvc