apiVersion: batch/v1
kind: Job
metadata:
  name: reps-build
  namespace: reps-prod
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - jackie

      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:v1.24.0
          # image: gcr.io/kaniko-project/executor:debug
          env:
            - name: DOCKER_CONFIG
              value: /kaniko/.docker
          args:
            - --context=https://codeload.github.com/Oktobrfest/doSomeReps/tar.gz/refs/heads/master          
            - --dockerfile=Dockerfile
            - --build-arg=NODE_ENV=prod
            - --skip-unused-stages
            - --context-sub-path=doSomeReps-master
            - --destination=docker.io/oktobrfest/reps:latest
            # Optional caching:
            - --cache=true         
            - --cache-repo=docker.io/oktobrfest/reps-cache
            - --compressed-caching=false # for low RAM PCs this is actually faster as 'false'
            - --snapshot-mode=time #redo #full #time is fastest, redo is experimental
            - --verbosity=info
            - --log-format=text
            - --log-timestamp
            - --push-retry=5 
            # - --registry-mirror=https://mirror.gcr.io
            - --registry-mirror=mirror.gcr.io

          resources:
            requests:
              cpu: "500m"            
              memory: "3Gi"
              ephemeral-storage: "8Gi"
            limits:
              cpu: "4000m"           
              memory: "8Gi"
              ephemeral-storage: "15Gi"

          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
            - name: kaniko-cache
              mountPath: /kaniko/cache
              
      volumes:
        - name: docker-config
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: kaniko-cache
          emptyDir:
            sizeLimit: 15Gi
