apiVersion: v1
kind: Secret
metadata:
  name: reps-prod-secrets
  namespace: reps-prod
type: Opaque
stringData:
  SECRET_KEY: ""

  # routing
  # PORT: "5557"

  # db
  DB_NAME: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""
  DB_HOST: ""
  # DB_PORT: 5432
  DRIVER: ""

  # s3
  ACCESS_KEY_ID: ""
  SECRET_ACCESS_KEY: ""
  BUCKET: ""
  REGION_NAME: ""