"""initial

Revision ID: b5c51318dc36
Revises: 
Create Date: 2026-05-09 00:02:13.861574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c51318dc36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['category_name'])
    op.add_column('users', sa.Column('ai_provider', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('ai_model', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('ai_api_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('ai_api_base', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_api_base')
    op.drop_column('users', 'ai_api_key')
    op.drop_column('users', 'ai_model')
    op.drop_column('users', 'ai_provider')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
